#!/bin/bash

properties() {
  for var in "${!KAFKA_@}"; do
     PROPERTY=$(echo ${var,,} | tr '_' '.')
     PROPERTY="${PROPERTY:6}"
     echo "$PROPERTY=${!var}"
  done
}

properties > '/opt/kafka/config/server.properties'

for rc in /etc/rc3.d/S*; do
  (bash $rc start)&
done

echo '// waiting forever'
sleep infinity
