#!/bin/bash

properties() {
  for VAR in "${!KAFKA_@}"; do
     PROPERTY=$(echo ${VAR,,} | tr '_' '.')
     echo "${PROPERTY:6}=${!VAR}"
  done
}

properties > '/opt/kafka/config/server.properties'

/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
