version: '2'

services:

  broker:
    hostname: broker1
    image: macthegif/kafka:test
    environment:
      KAFKA_CLUSTER_ID: 9erof1AKQlSi2WQiREBVSA
      KAFKA_NODE_ID: 1
      KAFKA_CONF_DIR: /data/config
      KAFKA_LOG_DIRS: /data/logs
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${HOSTNAME}:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@${HOSTNAME}:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
    volumes:
      - 'data:/data'
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - lan

volumes:
  data: {}

networks:
  lan: {}
