version: '2'

services:

  zookeeper:
    hostname: zookeeper
    image: zookeeper:latest
    networks:
      - lan

  kafka:
    hostname: kafka
    image: kafka:test
    env_file:
      - './security/kafka.pass'
    environment:
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:29092,SSL://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:29092,SSL://kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,SSL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_SSL_KEYSTORE_LOCATION: '/opt/kafka/security/kafka.jks'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/opt/kafka/security/trust.jks'
    volumes:
      - ./root:/root
      - ./security:/opt/kafka/security
    ports:
      - "29092:29092"
      - "29093:29093"
    networks:
      - lan

networks:
  lan:

# https://rmoff.net/2018/08/02/kafka-listeners-explained/
#
# remember to add host 'kafka' to /etc/hosts
#
# KAFKA_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092
# KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092
# KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
# KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
