version: '2'

services:

  kafka:
    hostname: kafka
    image: kafka:latest
    environment:
      KAFKA_LISTENERS: INTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - ./root:/root
    ports:
      - "29092:9092"
    networks:
      - lan

networks:
  lan:

# https://rmoff.net/2018/08/02/kafka-listeners-explained/
#
# remember to add host 'kafka' to /etc/hosts
#
