version: '2'

services:

  zookeeper:
    hostname: zookeeper
    image: zookeeper:latest
    environment:
      ZOO_MY_ID: 1
    volumes:
      - 'volume_zookeeper_data:/data'
      - 'volume_zookeeper_log:/datalog'
    networks:
      - lan

  kafka:
    hostname: kafka
    image: kafka:test
    env_file:
      - './security/keystores.pass'
      - './kafka.env'
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_LISTENERS: SECURE://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: SECURE://kafka:29093

    volumes:
      - './root:/root'
      - './security:/opt/kafka/security'
      - 'volume_kafka:/data'
    ports:
      - "29093:29093"
    networks:
      - lan

volumes:
  volume_zookeeper_data:
  volume_zookeeper_log:
  volume_kafka:

networks:
  lan:

# https://rmoff.net/2018/08/02/kafka-listeners-explained/
#
# remember to add host 'kafka' to /etc/hosts
#
# KAFKA_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092
# KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092
# KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
# KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
