FROM oraclelinux:8.5

RUN dnf install -q -y java

RUN groupadd kafka --gid 1000
RUN useradd kafka --uid 1000 --gid 1000

COPY kafka_2.13-3.5.1/ /opt/kafka/
COPY bootstrap /

RUN mkdir /data
RUN mkdir -p /opt/kafka
RUN chown -R kafka:kafka /data /opt/kafka

USER kafka

# These are image defaults, 
# they can be overridden in containers

ENV KAFKA_CLUSTER_ID=XXXXXXXXXX
ENV KAFKA_NODE_ID=1
ENV KAFKA_CONF_DIR=/data/config
ENV KAFKA_LOG_DIRS=/data/logs
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
ENV KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
ENV KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
ENV KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
ENV KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=300000
ENV KAFKA_LOG_RETENTION_HOURS=168
ENV KAFKA_LOG_SEGMENT_BYTES=1073741824
ENV KAFKA_NUM_IO_THREADS=8
ENV KAFKA_NUM_NETWORK_THREADS=3
ENV KAFKA_NUM_PARTITIONS=1
ENV KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR=1
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_PROCESS_ROLES=broker,controller
ENV KAFKA_SOCKET_RECEIVE_BUFFER_BYTES=102400
ENV KAFKA_SOCKET_REQUEST_MAX_BYTES=104857600
ENV KAFKA_SOCKET_SEND_BUFFER_BYTES=102400
ENV KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
ENV KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1

CMD /bootstrap
