version: '2'

services:

  zookeeper:
    hostname: zookeeper
    image: zookeeper:latest
    environment:
      ZOO_MY_ID: 1
    volumes:
      - 'volume_zookeeper_data:/data'
      - 'volume_zookeeper_log:/datalog'
    networks:
      - lan

  kafka:
    hostname: kafka
    image: kafka:test
    env_file:
      - './security/keystores.pass'
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_LOG_DIRS: '/data'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:29092,SSL://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:29092,SSL://kafka:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,SSL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_SSL_PROTOCOL: TLS
      KAFKA_SSL_ENABLED_PROTOCOLS: TLSv1.2,TLSv1.1,TLSv1
      # KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 
      KAFKA_SSL_KEYMANAGER_ALGORITHM: SunX509
      KAFKA_SSL_TRUSTMANAGER_ALGORITHM: PKIX
      KAFKA_SSL_KEYSTORE_TYPE: JKS
      KAFKA_SSL_TRUSTSTORE_TYPE: JKS
      KAFKA_SSL_KEYSTORE_LOCATION: '/opt/kafka/security/kafka.jks'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/opt/kafka/security/trust.jks'
      KAFKA_SSL_CLIENT_AUTH: required

    volumes:
      - ./root:/root
      - ./security:/opt/kafka/security
      - 'volume_kafka:/data'
    ports:
      - "29092:29092"
      - "29093:29093"
    networks:
      - lan

volumes:
  volume_zookeeper_data:
  volume_zookeeper_log:
  volume_kafka:

networks:
  lan:

# https://rmoff.net/2018/08/02/kafka-listeners-explained/
#
# remember to add host 'kafka' to /etc/hosts
#
# KAFKA_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092
# KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092
# KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
# KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
