FROM oraclelinux:8.5

RUN dnf install -q -y tar java gettext openssl librdkafka

RUN useradd kafka -m
RUN usermod -aG wheel kafka

COPY ./kafka*.tgz  /tmp/
RUN tar -C /opt -xzf /tmp/*.tgz
RUN mv /opt/kafka_*/ /opt/kafka/
RUN rm -f /etc/rc3.d/*
COPY ./rc/* /etc/rc3.d/
COPY bootstrap /

# These are image defaults, 
# they can be overridden in containers

ENV KAFKA_BROKER_ID=0
ENV KAFKA_NUM_NETWORK_THREADS=3
ENV KAFKA_NUM_IO_THREADS=8
ENV KAFKA_SOCKET_SEND_BUFFER_BYTES=102400
ENV KAFKA_SOCKET_RECEIVE_BUFFER_BYTES=102400
ENV KAFKA_SOCKET_REQUEST_MAX_BYTES=104857600
ENV KAFKA_LOG_DIRS=/tmp/kafka-logs
ENV KAFKA_NUM_PARTITIONS=1
ENV KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR=1
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
ENV KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
ENV KAFKA_LOG_RETENTION_HOURS=168
ENV KAFKA_LOG_SEGMENT_BYTES=1073741824
ENV KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=300000
ENV KAFKA_ZOOKEEPER_CONNECT=localhost:2181
ENV KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=18000

CMD /bootstrap
